use_frameworks!

platform :ios, '8.0'

target 'ZXPageView_Example' do
  pod 'ZXPageView', :path => '../'
  pod 'SnapKit', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.1.16'
  pod 'SwifterSwift', '~> 5.0.0'
  
  target 'ZXPageView_Tests' do
    inherit! :search_paths

    
  end
end
